source 'https://rubygems.org'

ruby '~> 2.5.5'

# https://rubygems.org/gems/jekyll
gem 'jekyll', '>= 3.8.5'

# https://rubygems.org/gems/minima
gem 'minima', '>= 2.5.0'

# https://rubygems.org/gems/jekyll-theme-cayman
gem 'jekyll-theme-cayman', '>= 0.1.1'

# https://rubygems.org/gems/github-pages/
gem 'github-pages', '>= 198', group: :jekyll_plugins

# https://rubygems.org/gems/tzinfo-data
gem 'tzinfo-data', '>= 1.2019.2', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# https://rubygems.org/gems/wdm
gem 'wdm', '~> 0.1.1' if Gem.win_platform?

group :jekyll_plugins do

    # https://rubygems.org/gems/jekyll-feed
    gem 'jekyll-feed', '>= 0.11.0'

end
