#
# The MIT License (MIT)
#
# Copyright (C) 2019 Alexander Kapitman <akman.ru@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

source 'https://rubygems.org'

ruby '~> 2.7.1'

# https://rubygems.org/gems/jekyll
gem 'jekyll', '>= 3.8.7'

# https://rubygems.org/gems/minima
gem 'minima', '>= 2.5.1'

# https://rubygems.org/gems/jekyll-theme-cayman
gem 'jekyll-theme-cayman', '>= 0.1.1'

# https://rubygems.org/gems/github-pages/
gem 'github-pages', '>= 206', group: :jekyll_plugins

# https://rubygems.org/gems/tzinfo-data
gem 'tzinfo-data', '>= 1.2019.3', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# https://rubygems.org/gems/tzinfo
gem 'tzinfo', '~> 1.1'

# https://rubygems.org/gems/wdm
gem 'wdm', '~> 0.1.1' if Gem.win_platform?

# https://rubygems.org/gems/nokogiri
gem 'nokogiri', '>= 1.11.0.rc2'

# https://rubygems.org/gems/faraday
gem 'faraday', '~> 0.17.3'

# https://rubygems.org/gems/activesupport
gem "activesupport", ">= 6.0.3.1"

group :jekyll_plugins do

    # https://rubygems.org/gems/jekyll-feed
    gem 'jekyll-feed', '>= 0.13.0'

    # https://rubygems.org/gems/jekyll-seo-tag
    gem 'jekyll-seo-tag', '>= 2.6.1'

    # https://rubygems.org/gems/jekyll-target-blank
    gem 'jekyll-target-blank', '>= 2.0.0'

end
